service:
  name: serverless-vault-plugin

provider:
  name: aws
  stage: "develop"
  region: "us-east-1"



plugins:
  modules:
    - ./index.js


custom:
  secrets:
    aws: 'path/to/secret'
    otherPluginSecret: 'path/to/secret:response.path.to.object.property'

  vault:
    host: ${env:VAULT_HOST}
    debugQuery: false
    auth:
      #roleId: ${env:VAULT_AUTH_ROLEID}
      #secretId: ${env:VAULT_AUTH_SECRETID}
      # OR
      #useToken: ${env:VAULT_AUTH_USETOKEN}
    aws:
      setEnvVars: true
      secretPath: ${env:VAULT_AWS_SECRETPATH}

  # HOW TO RESOLVE ANOTHER SECRET
  #otherPluginConf:
    #secret: ${vault:${self:custom.secrets.otherPluginSecret}}